export const MOTIVATION_QUOTES = [
  "Consistency beats intensity.",
  "You never skip twice.",
  "Show up, no matter what.",
  "Discipline creates freedom.",
  "Future you is watching.",
  "Motivation follows action.",
  "Hard days create strong people.",
  "Showing up is the win.",
  "No zero days.",
  "Small progress is still progress.",
  "Train the mind, the body follows.",
  "One rep at a time.",
  "Your only competition is yesterday.",
  "Sweat is just fat crying.",
  "The pain you feel today is strength tomorrow.",
  "Stop wishing. Start doing.",
  "Earn your body.",
  "The grind doesn't stop.",
  "Strong is the new sexy.",
  "Build the habit. Become unstoppable.",
  "Excuses don't burn calories.",
  "Be stronger than your strongest excuse.",
  "Quitters never win, winners never quit.",
  "Don't count the days, make the days count.",
  "If it doesn't challenge you, it doesn't change you.",
  "Pain is temporary. Pride is forever.",
  "Wake up. Work out. Win.",
  "You are your only limit.",
  "Train insane or remain the same.",
  "Push yourself, no one else will.",
  "Success starts with self-discipline.",
  "Suffer the pain of discipline or the pain of regret.",
  "The body achieves what the mind believes.",
  "Don't stop when you're tired. Stop when you're done.",
  "Make yourself proud.",
  "Hustle for that muscle.",
  "Sore today, strong tomorrow.",
  "Be the energy you want to attract.",
  "Greatness is a lot of small things done well.",
  "Showing up beats showing off.",
  "Comfort is the enemy of progress.",
  "Become 1% better every day.",
  "The first step is hardest. Take it.",
];
